spring.application.name=eureka-server
server.port=8761

# ele não precisa se registrar nele mesmo nem buscar outros registros, ele É o registro
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
